name: CODEOWNERs Superpowers

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  codeowners-superpowers:
    runs-on: ubuntu-latest
    name: 检查所有代码负责人是否已审批
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Verify CODEOWNERs and Changed Files
        uses: endersonmenezes/codeowners-superpowers@main
        with:
          super_power: "require-all-codeowners"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
          owner_and_repository: ${{ github.repository }}
